### ISSUE TITLE
Support for `Cross.toml` configs

### ISSUE THREAD

**Issue by redeexpressos** [rust-embedded/meta-rust-bin#186]
Trying to build a crate that depends on `protoc`. When cross-compiling, I have to add `Cross.toml`:
```toml
[build]
default-target = "armv7-unknown-linux-gnueabihf"
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get --assume-yes install protobuf-compiler:$CROSS_DEB_ARCH",
]
```

How can I add that configuration when compiling with this layer?
