### ISSUE TITLE
missing --sysroot argument for link-arg?

### ISSUE THREAD

**Issue by sprhawk** [rust-embedded/meta-rust-bin#95]
Somehow, my previously worked project now doesn't, only if I added rustflag as:
```
EXTRA_RUSTFLAGS += "-C link-arg=--sysroot=${WORKDIR}/recipe-sysroot"
```
in recipe, it will pass compilation.

if not added, it will report error:
```
cannot find crti.o: No such file or directory
cannot find crtbeginS.o: No such file or director
cannot find Scrt1.o: No such file or directory
```

**Comment by nastevens** [comment]
The `--sysroot` is actually being provided through the wrappers used during build. A cargo config file like the following is written out:

```toml
[target.x86_64-unknown-linux-gnu]
linker = '/home/nick/dev/meta-rust-bin-testing/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/exa/0.9.0-r0/wrappers/linker-native-wrapper.sh'

[target.armv7-unknown-linux-gnueabihf]
linker = '/home/nick/dev/meta-rust-bin-testing/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/exa/0.9.0-r0/wrappers/linker-wrapper.sh'

...
```

Looking inside of the `linker-wrapper.sh` script you should see something like:
```sh
arm-poky-linux-gnueabi-gcc  -march=armv7ve -mthumb -mfpu=neon -mfloat-abi=hard -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/home/nick/dev/meta-rust-bin-testing/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/exa/0.9.0-r0/recipe-sysroot -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -fstack-protector-strong -Wl,-z,relro,-z,now "$@"
```

So during the Rust linking step it's calling out to the wrapper script, which does include the `--sysroot` option.

I'm going to close because I believe everything is working as intended, but please feel free to re-open with additional information!
